name: 📝 Backlog Item
description: Erstellen eines neuen Backlog Items für das Projekt
title: '[BACKLOG] - '
labels: [backlog]
body:
  - type: markdown
    attributes:
      value: |
        Bitte fülle die folgenden Informationen aus, um ein neues Backlog Item für das Projekt zu erstellen.
  - type: textarea
    id: beschreibung
    attributes:
      label: Beschreibung
      description: Gib eine detaillierte Beschreibung des Projekts an. Was soll umgesetzt werden und warum?
      placeholder: Detaillierte Beschreibung hier...
    validations:
      required: true
  - type: textarea
    id: akzeptanzkriterien
    attributes:
      label: Akzeptanzkriterien
      description: Definiere klare Akzeptanzkriterien für dieses Backlog Item. Verwende die Markdown-Checkbox-Syntax (- [ ]) für jedes Kriterium.
      placeholder: |
        - [ ] Kriterium 1
        - [ ] Kriterium 2
        - [ ] Kriterium 3
    validations:
      required: true
  - type: textarea
    id: checkliste
    attributes:
      label: Checkliste
      description: Definiere eine detaillierte Checkliste für die Entwicklung dieses Backlog Items. Verwende die Markdown-Checkbox-Syntax (- [ ]) für jede Aufgabe.
      placeholder: |
        - [ ] Beispiel 1
        - [ ] Beispiel 2
        - [ ] Beispiel 3
        - [ ] Beispiel 4
        - [ ] Beispiel 5
        - [ ] Beispiel 6
        - [ ] Beispiel 7
        - [ ] Beispiel 8
        - [ ] Beispiel 9
    validations:
      required: true
  - type: dropdown
    id: prioritaet
    attributes:
      label: Priorität
      description: Wähle die Priorität dieses Backlog Items.
      options:
        - Niedrig
        - Mittel
        - Hoch
        - Kritisch
    validations:
      required: true
  - type: checkboxes
    id: labels
    attributes:
      label: Zusätzliche Labels
      description: Wähle alle zutreffenden Labels für dieses Backlog Item.
      options:
        - label: Bug
        - label: Feature
        - label: Verbesserung
        - label: Dokumentation
