<Construction>:
    
    BackgroundLayout:
    
    NavLayout:
        size_hint_x: None
        width: '250dp'

    MDBoxLayout:
        orientation: 'vertical'
        padding: dp(50)
        spacing: dp(-100)
        
        Image:
            source: "resources/baustella.gif"
            #fit_mode: "contain"
            
            
        MDLabel:
            text: "Hier ist noch Baustella"
            halign: 'center'
            font_style: "Display"
            #valign: 'middle'
